version: '3'

services:
  gateway:
    image: az3z3l/fus-nginx
    links:
      - fmanage:fmanage
      - login:login
      - register:register
    ports:
      - "1337:80"

  fmanage:
    image: az3z3l/fus-fmanage
    env_file:
      - ./secrets/vars.env
    expose:
      - "80"

  login:
    image: az3z3l/fus-login
    env_file:
      - ./secrets/vars.env
    expose:
      - "80"

  register:
    image: az3z3l/fus-register
    env_file:
      - ./secrets/vars.env
    links:
      - mailer:mailer
    expose:
      - "80"


  mailer:
    image: az3z3l/fus-mailer
    env_file:
      - ./secrets/vars.env
    expose:
      - "80"

