version: '3'

services:
  gateway:
    image: nginx:latest
    links:
      - fmanage:fmanage
      - login:login
      - register:register
    ports:
      - "1337:80"
    volumes:
      - ./nginxx/nginx.conf:/etc/nginx/nginx.conf
  
  fmanage:
    build: ./fmanage/.
    env_file:
      - vars.env
    expose:
      - "80"

  login:
    build: ./login/.
    env_file:
      - vars.env
    expose:
      - "80"

  register:
    build: ./register/.
    env_file:
      - vars.env
    links:
      - mailer:mailer
    expose:
      - "80"


  mailer:
    build: ./mailer/.
    env_file:
      - vars.env
    expose:
      - "80"

