version: '2'

services:
  gateway:
    image: nginx:latest
    links:
      - fmanage
      - login
      - register
    ports:
      - "1337:80"
    volumes:
      - ./nginxx/nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - fmanage
    #   - login
    #   - register
  
  fmanage:
    build: ./fmanage/.
  
  login:
    build: ./login/.

  register:
    build: ./register/.